import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartProvider from "@/context/CartProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between py-3 px-5 container mx-auto items-center">
          <Link href="/">
            <h2 className="text-3xl text-cyan-600">Smart Kitchen 🔪</h2>
          </Link>
          <div>
            <Link href="/foods" className="mr-4 btn">
              Foods
            </Link>
            <Link href="/review" className="mr-4 btn">
              Review
            </Link>
          </div>
        </header>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
