import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartProvider from "@/context/CartProvider";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// google font roboto
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

// metadata
export const metadata = {
  title: {
    default: "Smart Kitchen",
    template: "%s | Smart Kitchen",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} `}
      >
        <header className="flex justify-between py-3 px-5 container mx-auto items-center">
          <Link href="/">
            <h2 className="text-3xl text-cyan-600">Smart Kitchen 🔪</h2>
          </Link>
          <div>
            <Button variant="outline">
              <Link href="/foods" className="mr-4 ">
                Foods
              </Link>
            </Button>
            <Button variant="outline">
              <Link href="/review" className="mr-4 ">
                Review
              </Link>
            </Button>
          </div>
        </header>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
