import React from "react";
import ReviewPage from "./ReviewPage";

export const metadata = {
  title: "All Reviews",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <ReviewPage />;
    </div>
  );
};

export default page;
